apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx-app-ns
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>NGINX App - ArgoCD</title>
    </head>
    <body>
        <h1>🚀 NGINX App funcionando!</h1>
        <p>Desplegado con ArgoCD</p>
        <p>Namespace: nginx-app-ns</p>
        <p>Ingress: nginx-app.local</p>
    </body>
    </html>