---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-bbdd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 13.2.22
    - repoURL: https://github.com/VanGoMu/argo_app.git
      targetRevision: HEAD
      path: bbdd
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ddbb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
