apiVersion: v2
name: postgres-bbdd
description: PostgreSQL database for application using Bitnami chart
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: 13.2.22
    repository: https://charts.bitnami.com/bitnami
