namespace: ddbb
postgres:
  image: postgres:15.4
  username: postgres
  password: mysecretpassword
  database: appdb
  storage:
    size: 15Gi
    storageClass: standard
service:
  type: ClusterIP
  port: 5432
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
